version: "3.7"
x-minio-common: &minio-common
  image: quay.io/minio/minio:RELEASE.2022-09-17T00-09-45Z
  command: server --console-address ":9001" http://minio{1...2}/data{1...2}
  restart: unless-stopped
  expose:
    - 9000
    - 9001
  environment:
    - MINIO_ROOT_USER=${MINIO_USER}
    - MINIO_ROOT_PASSWORD=${MINIO_PASSWORD}
  healthcheck:
    test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
    interval: 30s
    timeout: 20s
    retries: 3

services:
  minio1:
    <<: *minio-common
    hostname: minio1
    volumes:
      - data1-1:/data1
      - data1-2:/data2

  minio2:
    <<: *minio-common
    hostname: minio2
    volumes:
      - data2-1:/data1
      - data2-2:/data2
  upload_app:
    image: mohammedwazier/upload_app:latest
    restart: always
    volumes:
      - app_vol:/app
    ports:
      - ${PORT}:${PORT}
    env_file:
      - .env
  nginx:
    image: "jc21/nginx-proxy-manager:latest"
    restart: unless-stopped
    ports:
      # These ports are in format <host-port>:<container-port>
      - 80:80 # Public HTTP Port
      - 443:443 # Public HTTPS Port
      - 81:81 # Admin Web Port
      # Add any other Stream port you want to expose
    environment:
      # Mysql/Maria connection parameters:
      DB_MYSQL_HOST: "db"
      DB_MYSQL_PORT: 3306
      DB_MYSQL_USER: "npm"
      DB_MYSQL_PASSWORD: "npm"
      DB_MYSQL_NAME: "npm"
    volumes:
      - ./data:/data
      - ./letsencrypt:/etc/letsencrypt
    depends_on:
      - db
  db:
    image: "jc21/mariadb-aria:latest"
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: "npm"
      MYSQL_DATABASE: "npm"
      MYSQL_USER: "npm"
      MYSQL_PASSWORD: "npm"
    volumes:
      - mariadb:/var/lib/mysql
  # nginx:
  #   image: nginx:1.22.0-alpine
  #   hostname: nginx
  #   restart: unless-stopped
  #   environment:
  #     - NGINX_HOST=${MAIN_HOST}
  #     - NGINX_ENVSUBST_OUTPUT_DIR=/etc/nginx
  #   volumes:
  #     - ./nginx/template:/etc/nginx/templates
  #   ports:
  #     - 80:80
  #     - 9000:9000
  #     - 9001:9001
  #   expose:
  #     - 9000
  #     - 9001
  #     - 80
  #   links:
  #     - minio1
  #     - minio2
  #     - upload_app
  #   depends_on:
  #     - minio1
  #     - minio2
  #     - upload_app
volumes:
  data1-1:
  data1-2:
  data2-1:
  data2-2:
  app_vol:
  mariadb:
